// <auto-generated />
using System;
using CodeWhispererAI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeWhispererAI.Migrations
{
    [DbContext(typeof(CodeWhispererAIContext))]
    [Migration("20231107180211_DBInitial")]
    partial class DBInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeWhispererAI.Models.CodeAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("APIQuery")
                        .HasColumnType("text")
                        .HasColumnName("api_query");

                    b.Property<string>("Analysis")
                        .HasColumnType("text")
                        .HasColumnName("analysis");

                    b.Property<int>("CodeId")
                        .HasColumnType("integer")
                        .HasColumnName("code_id");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_code_analyses");

                    b.ToTable("code_analyses", (string)null);
                });

            modelBuilder.Entity("CodeWhispererAI.Models.CodeSnippet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeInputted")
                        .HasColumnType("text")
                        .HasColumnName("code_inputted");

                    b.Property<int>("FeedbackID")
                        .HasColumnType("integer")
                        .HasColumnName("feedback_id");

                    b.Property<string>("LanguageUsed")
                        .HasColumnType("text")
                        .HasColumnName("language_used");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.HasKey("Id")
                        .HasName("pk_code_snippets");

                    b.ToTable("code_snippets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
